### ISSUE TITLE
Packages for aoj miss some platforms for Java 9

### ISSUE THREAD

**Issue by marchof** [foojayio/discoapi#25]
# Actual

https://api.foojay.io/disco/v1.0/packages?distro=aoj&version=9&latest=overall

# Expected

The platforms `macos-x64`, `linux-arm64`should be reported, see:

https://adoptopenjdk.net/releases.html?variant=openjdk9

**Comment by marchof** [comment]
Just retested: Looks like the packages are still missing.

**Comment by geertjanw** [comment]
Gerrit will check and get back to you ASAP.

**Comment by marchof** [comment]
Just retested: Looks like the packages are still missing.

**Comment by HanSolo** [comment]
Hmm...just checked and Disco has the macos x64 and linux aarch64 packages available...

**Comment by HanSolo** [comment]
Yep that's correct because you asked for latest overall which is 9.04 in this case and that is not available for linux and macos. They are only available for 9. So if you use latest=available instead of latest=overall you should see them.
https://api.foojay.io/disco/v2.0/packages?version=9&distro=aoj&latest=available

**Comment by marchof** [comment]
Indeed, I forgot that there is now the `available` option and I'm also using it already:

https://javaalmanac.io/jdk/download/#product=aoj&version=9&type=jdk

So looks good for me now. Thx!
